spring:
  messages:
    basename: messages
  datasource:
    url: jdbc:h2:mem:deliverydb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always


mybatis:
  mapper-locations: classpath*:mapper/*.xml

jwt:
  secret: YmFyb2dvYmFja2VuZGhvbWV3b3JrdG9rZW5zZWNyZXRrZXlmb3Jsb2dpbmFwaWJhcm9nb2Jhcm9nbw==